Repository AY2223S2-CS2113-T12-3/tp, pull requests merged in 2023-03, with the labels that each got.

#19 Fix: Load data from txt file instead of csv file
  data/modules.txt
  data/universities.txt
  src/main/java/seedu/duke/DataReader.java
Labels: type.Bug, priority.Medium, severity.Medium

#23 Added support in UI function for delete functionality
  data/saved_modules.txt
  src/main/java/seedu/duke/UI.java
  src/main/resources/META-INF/MANIFEST.MF
Labels: type.Task, priority.High

#25 Added print logo when code first executes
  data/saved_modules.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low, severity.Low

#28 Add UI print functions in executeUserCommand function
  data/saved_modules.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#32 Add command class to allow Parser to return commands to be executed
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/AddModuleCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/ListCurrentCommand.java
  src/main/java/seedu/duke/command/ListPuCommand.java
  src/main/java/seedu/duke/command/ListPuModulesCommand.java
  src/test/java/seedu/duke/command/AddModuleCommandTest.java
Labels: type.Enhancement, priority.Medium

#33 Added help function
  data/saved_modules.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/test/java/seedu/duke/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#34 Fixed bugs and relocated deletemodule function
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/DeleteModuleCommand.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/command/AddModuleCommandTest.java
Labels: type.Bug, priority.High, severity.Medium

#35 Create Exceptions class and add exceptions in Parser class
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/ExceptionHandleCommand.java
  src/main/java/seedu/duke/exceptions/InvalidCommandException.java
  src/main/java/seedu/duke/exceptions/InvalidModuleException.java
  src/main/java/seedu/duke/exceptions/InvalidPuException.java
Labels: type.Enhancement, type.Bug, priority.High

#36 Enhance function in Parser and UI
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/ExceptionHandleCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/ListCurrentCommand.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task, priority.Medium

#45 Add JUnit testing and make minor modifications in Parser
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#46 Edited Junit5 testing in UI
  data/saved_modules.txt
  src/test/java/seedu/duke/UITest.java
Labels: type.Bug, priority.High, severity.High

#47 Update DG
  data/saved_modules.txt
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/diagrams/style.puml
  src/test/java/seedu/duke/UITest.java
Labels: type.Enhancement, priority.Medium

#53 [Task] Developer guide Architecture and List Commands
  data/saved_modules.txt
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.png
  docs/diagrams/Architecture.puml
  docs/diagrams/ListCurrentCommandSequenceDiagram.png
  docs/diagrams/ListCurrentCommandSequenceDiagram.puml
  docs/diagrams/ListPuCommandSequenceDiagram.png
  docs/diagrams/ListPuCommandSequenceDiagram.puml
  docs/diagrams/ListPuModulesCommandSequenceDiagram.png
  docs/diagrams/ListPuModulesCommandSequenceDiagram.puml
  docs/img.png
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
Labels: type.Enhancement, type.Task, priority.High, severity.VeryLow, severity.Medium

#51 Branch Create budget planner Class with JUnit for all classes in budget package
  .gitignore
  src/main/java/seedu/duke/DatabaseInterface.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/budget/Accommodation.java
  src/main/java/seedu/duke/budget/AirplaneTicket.java
  src/main/java/seedu/duke/budget/BudgetPlanner.java
  src/main/java/seedu/duke/budget/BudgetStorage.java
  src/main/java/seedu/duke/budget/Entertainment.java
  src/main/java/seedu/duke/budget/Food.java
  src/main/java/seedu/duke/budget/GoodsAndServices.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/EditAccommodationCommand.java
  src/main/java/seedu/duke/command/EditAirplaneTicketCommand.java
  src/main/java/seedu/duke/command/EditBudgetCommand.java
  src/main/java/seedu/duke/command/EditCostCommand.java
  src/main/java/seedu/duke/command/EditEntertainmentCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
  src/main/java/seedu/duke/command/ViewBudgetCommand.java
  src/test/java/seedu/duke/budget/AccommodationTest.java
  src/test/java/seedu/duke/budget/AirplaneTicketTest.java
  src/test/java/seedu/duke/budget/BudgetPlannerTest.java
  src/test/java/seedu/duke/budget/BudgetStorageTest.java
  src/test/java/seedu/duke/budget/EntertainmentTest.java
  src/test/java/seedu/duke/budget/FoodTest.java
  src/test/java/seedu/duke/command/AddModuleCommandTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
Labels: type.Story, type.Task, priority.High

#55 Add deadlines functionality and reminder functionality
  .gitignore
  src/main/java/seedu/duke/Deadline.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/AddDeadlineCommand.java
  src/main/java/seedu/duke/command/AddModuleCommand.java
  src/main/java/seedu/duke/command/DeleteDeadlineCommand.java
  src/main/java/seedu/duke/command/ListDeadlinesCommand.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
Labels: type.Story, priority.Medium, severity.High

#63 [Enchancement] Changed remove function and list current function
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/ListCurrentCommand.java
  src/main/java/seedu/duke/command/ListCurrentPuCommand.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ListCurrentCommandTest.java
Labels: type.Enhancement, priority.High, priority.Medium, severity.High

#66 Complete Issues #49, #61 ,and #65
  src/main/java/seedu/duke/Parser.java
Labels: type.Enhancement, type.Bug, priority.High, priority.Medium

#67 add User Guide Budget commands #68 Issues
  docs/UserGuide.md
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/EditAccommodationCommand.java
  src/main/java/seedu/duke/command/EditAirplaneTicketCommand.java
  src/main/java/seedu/duke/command/EditBudgetCommand.java
  src/main/java/seedu/duke/command/EditEntertainmentCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
  src/main/java/seedu/duke/command/ViewBudgetCommand.java
Labels: type.Task, priority.High

#70 [Enhancement] Update /help command
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, priority.Medium

#77 Update UG with list [PU ABBRV] or list [PU INDEX] and search [NUS MOD…
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#75 Update DG and fix bug #74
  data/saved_modules.txt
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/diagrams/DeleteModuleCommandSequenceDiagram.png
  docs/diagrams/DeleteModuleCommandSequenceDiagram.puml
  docs/diagrams/HelpCommandSequenceDiagram.png
  docs/diagrams/HelpCommandSequenceDiagram.puml
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High

#78 [Task] Add and edited DG for list functions
  docs/DeveloperGuide.md
  docs/diagrams/ListCurrentCommandSequenceDiagram.png
  docs/diagrams/ListCurrentCommandSequenceDiagram.puml
  docs/diagrams/ListCurrentPuCommandSequenceDiagram.png
  docs/diagrams/ListCurrentPuCommandSequenceDiagram.puml
  src/main/java/seedu/duke/command/ListCurrentPuCommand.java
Labels: type.Task, priority.Medium, severity.Low

#79 [Task] Added user guide for list functions and remove function
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.Low

#83 Update help function and format code
  src/main/java/seedu/duke/Deadline.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Module.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/ExceptionHandleCommand.java
  src/main/java/seedu/duke/command/ListCurrentPuCommand.java
  src/main/java/seedu/duke/command/ListFoundNusModsCommand.java
  src/main/java/seedu/duke/command/ListPuModulesCommand.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#85 Add Parser Sequence Diagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/ParserSequenceDiagram.png
  docs/diagrams/ParserSequenceDiagram.puml
Labels: type.Task, priority.Medium

#87 Fix bug in add deadline function
  META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High

#89 Update UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium, severity.VeryLow, severity.Low
