Repository AY2223S2-CS2113-T12-3/tp, pull requests merged in 2023-04, with the labels that each got.

#142 Update User Guide to include add command and change budget command format
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#143 [Enhancement] Disallow duplicate module mappings to be saved to database Issue #120
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/AddModuleCommand.java
Labels: type.Enhancement, priority.Medium

#145 [Bug] Fix database editing unhandled exceptions Issue #137, #109
  src/main/java/seedu/duke/DatabaseInterface.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/budget/BudgetStorage.java
Labels: type.Bug, priority.Medium, severity.Medium

#147 Fix bug and refactor code to DeadlineStorage
  src/main/java/seedu/duke/DeadlineStorage.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/AddDeadlineCommand.java
  src/main/java/seedu/duke/command/DeleteDeadlineCommand.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#149 Fix whitespace bugs for budget commands
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/budget/BudgetPlanner.java
  src/test/java/seedu/duke/budget/BudgetPlannerTest.java
Labels: type.Bug, priority.High, severity.Low

#150 Add deadline database corruption handling, Closes #128
  src/main/java/seedu/duke/DeadlineStorage.java
  src/main/java/seedu/duke/UI.java
Labels: type.Bug, priority.Medium

#151 Change printing functions sort
  docs/UserGuide.md
  src/main/java/seedu/duke/DataReader.java
  src/main/java/seedu/duke/Module.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/ListPuModulesCommand.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/ListCurrentCommandTest.java
  src/test/java/seedu/duke/command/ListCurrentPuCommandTest.java
  src/test/java/seedu/duke/command/ListPuCommandTest.java
  src/test/java/seedu/duke/command/ListPuModulesCommandTest.java
Labels: type.Enhancement, priority.High, severity.High

#153 Enhance parseCommand to remove multiple whitespaces
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  text-ui-test/input.txt
Labels: type.Enhancement, priority.Medium

#155 Add JUnit test for Parser class
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Task, priority.Medium

#157 Change BudgetPlanner and BudgetStorage into singleton pattern
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/budget/BudgetPlanner.java
  src/main/java/seedu/duke/budget/BudgetStorage.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/budget/BudgetPlannerTest.java
  src/test/java/seedu/duke/budget/BudgetStorageTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
Labels: type.Enhancement, priority.Medium

#158 Change Storage Class into singleton
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/command/AddModuleCommandTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
Labels: type.Enhancement, priority.Medium

#159 Change DeadlineStorage classs into singleton pattern
  src/main/java/seedu/duke/DeadlineStorage.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
Labels: type.Enhancement, priority.Medium

#156 Change Parser class into singleton pattern
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
Labels: type.Enhancement, priority.Medium

#161 Add budget developer guide and update storage developer guide
  docs/DeveloperGuide.md
  docs/diagrams/Storage/Storage.png
  docs/diagrams/Storage/Storage.puml
  docs/diagrams/Storage/StorageClassDiagram.png
  docs/diagrams/Storage/StorageClassDiagram.puml
  docs/diagrams/Storage/readModData.png
  docs/diagrams/Storage/readModData.puml
  docs/diagrams/budget/EditAccommodationCommand.png
  docs/diagrams/budget/EditAccommodationCommand.puml
  docs/diagrams/budget/EditAirplaneTicketCommand.png
  docs/diagrams/budget/EditAirplaneTicketCommand.puml
  docs/diagrams/budget/EditBudgetCommand.png
  docs/diagrams/budget/EditBudgetCommand.puml
  docs/diagrams/budget/EditEntertainmentCommand.png
  docs/diagrams/budget/EditEntertainmentCommand.puml
  docs/diagrams/budget/EditFoodCommand.png
  docs/diagrams/budget/EditFoodCommand.puml
  docs/diagrams/budget/ViewBudgetCommand.png
  docs/diagrams/budget/ViewBudgetCommand.puml
  docs/diagrams/budget/budgetClassDiagram.png
  docs/diagrams/budget/budgetClassDiagram.puml
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/budget/GoodsAndServices.java
  src/main/java/seedu/duke/command/EditAccommodationCommand.java
  src/main/java/seedu/duke/command/EditAirplaneTicketCommand.java
  src/main/java/seedu/duke/command/EditBudgetCommand.java
  src/main/java/seedu/duke/command/EditEntertainmentCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
Labels: type.Enhancement, priority.High

#164 Draft PPP and update UG
  docs/UserGuide.md
  docs/team/darrenlsx.md
Labels: type.Enhancement, priority.Low, severity.VeryLow

#152 Change add function to use index
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Task, priority.Medium, severity.Medium

#165 Update JUnit test and update help function
  src/main/java/seedu/duke/Deadline.java
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/AddDeadlineCommandTest.java
  src/test/java/seedu/duke/command/DeleteDeadlineCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#166 Fix UG bug
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.VeryLow

#167 Max ppp draft1
  docs/team/muxpotato.md
Labels: type.Enhancement, priority.Low, severity.Low

#168 Cleanup budget
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Task, priority.Medium

#169 Clean up UG and UI help function
  docs/UserGuide.md
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.High

#171 Added commnad summary to UG, Touch up on UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low, severity.Low

#86 Add Assertions to Remove function
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
Labels: type.Enhancement, priority.Medium, severity.High

#172 Changed UI and DataReader to Singleton Design Pattern
  src/main/java/seedu/duke/DataReader.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/Command.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/DeleteDeadlineCommandTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ListFoundNusModsCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#174 Add JUnit tests and cleanup code and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/Storage.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/budget/BudgetStorageTest.java
  src/test/java/seedu/duke/command/EditAccommodationCommandTest.java
  src/test/java/seedu/duke/command/EditAirplaneTicketCommandTest.java
  src/test/java/seedu/duke/command/EditBudgetCommandTest.java
  src/test/java/seedu/duke/command/EditEntertainmentCommandTest.java
  src/test/java/seedu/duke/command/EditFoodCommandTest.java
  src/test/java/seedu/duke/command/ViewBudgetCommandTest.java
Labels: type.Task, priority.High

#175 Add exceptions to handle incorrect inputs for all the commands except…
  src/main/java/seedu/duke/Parser.java
Labels: type.Bug, priority.High

#176 [Task] Update DG for UI, Add and Delete Function
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.png
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.puml
  docs/diagrams/Commands/HelpCommandSequenceDiagram.png
  docs/diagrams/Commands/HelpCommandSequenceDiagram.puml
  docs/diagrams/Commands/ListCurrentCommandSequenceDiagram.png
  docs/diagrams/Commands/ListCurrentCommandSequenceDiagram.puml
  docs/diagrams/Commands/ListCurrentPuCommandPrintModuleDetailsSequenceDiagram.png
  docs/diagrams/Commands/ListCurrentPuCommandPrintModuleDetailsSequenceDiagram.puml
  docs/diagrams/Commands/ListCurrentPuCommandSequenceDiagram.png
  docs/diagrams/Commands/ListCurrentPuCommandSequenceDiagram.puml
  docs/diagrams/Commands/ListPuCommandSequenceDiagram.png
  docs/diagrams/Commands/ListPuCommandSequenceDiagram.puml
  docs/diagrams/Commands/ListPuModulesCommandSequenceDiagram.png
  docs/diagrams/Commands/ListPuModulesCommandSequenceDiagram.puml
  docs/diagrams/DeleteModuleCommandSequenceDiagram.png
  docs/diagrams/ListCurrentCommandSequenceDiagram.png
  docs/diagrams/ListCurrentPuCommandSequenceDiagram.png
  docs/diagrams/Miscellaneous/ExampleOfPrintFunctionsBeingHardToReadOneLine.png
  docs/diagrams/Miscellaneous/ExampleOfPrintFunctionsMoreReadable.jpg
  docs/diagrams/Miscellaneous/ExampleOfPrintFunctionsNotReadable.jpg
  docs/diagrams/Miscellaneous/SortModulesAccordingToPrintingLengthFunction.png
  docs/diagrams/Miscellaneous/SortModulesAccordingToPrintingLengthFunction.puml
  docs/diagrams/Storage/StorageAddModule.puml
  docs/diagrams/UIClassDiagram.png
  docs/diagrams/UIClassDiagram.puml
  src/main/java/seedu/duke/UI.java
Labels: type.Enhancement, priority.High, severity.VeryLow

#177 Add Acknowledgements for Junit5 testing for UI test
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.High, severity.VeryLow

#179 Update DG and edit credits for author
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Commands/DeleteDeadlineCommandSequenceDiagram.png
  docs/diagrams/Commands/DeleteDeadlineCommandSequenceDiagram.puml
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.png
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.puml
  src/main/java/seedu/duke/DeadlineStorage.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, priority.High, severity.Medium

#178 Enhance search command
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/ListMappableNusModsCommand.java
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Enhancement, priority.Medium

#180 Update developer guide for add module command, change budget commands to non case sensitive
  docs/DeveloperGuide.md
  docs/diagrams/Storage/StorageAddModule.png
  docs/diagrams/Storage/StorageAddModule.puml
  src/main/java/seedu/duke/Parser.java
Labels: type.Task

#181 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Commands/DeleteDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/AddDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/AddDeadlineCommandSequenceDiagram.puml
  docs/diagrams/Deadline/DeadlineClassDiagram.png
  docs/diagrams/Deadline/DeadlineClassDiagram.puml
  docs/diagrams/Deadline/DeleteDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/DeleteDeadlineCommandSequenceDiagram.puml
  docs/diagrams/Deadline/ListDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/ListDeadlineCommandSequenceDiagram.puml
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, type.Bug, priority.Medium, severity.High

#182 Update DG format and change case sensitivity
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Parser.java
Labels: type.Enhancement, type.Bug, priority.Medium, severity.High

#183 [Task] Add Value proposition and User Stories for Developer Guide
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.High, severity.Low

#184 Change filter commands to standardize with other commands, updated UG
  docs/UserGuide.md
  src/main/java/seedu/duke/Module.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Bug, priority.High

#185 Add assertion
  src/main/java/seedu/duke/DeadlineStorage.java
Labels: type.Enhancement, priority.Low, severity.VeryLow

#186 Change storage class name to ModuleStorage
  docs/DeveloperGuide.md
  docs/diagrams/Storage/StorageAddModule.png
  docs/diagrams/Storage/StorageAddModule.puml
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ModuleStorage.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/AddModuleCommand.java
  src/main/java/seedu/duke/command/DeleteModuleCommand.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/StorageTest.java
  src/test/java/seedu/duke/command/AddModuleCommandTest.java
  src/test/java/seedu/duke/command/DeleteDeadlineCommandTest.java
  src/test/java/seedu/duke/command/DeleteModuleCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/InvalidCommandTest.java
  src/test/java/seedu/duke/command/ListCurrentPuCommandTest.java
Labels: type.Task, priority.High

#187 Fix DG Seq Diagrams
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.png
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.puml
  docs/diagrams/Deadline/AddDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/AddDeadlineCommandSequenceDiagram.puml
  docs/diagrams/Deadline/DeleteDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/DeleteDeadlineCommandSequenceDiagram.puml
  docs/diagrams/Deadline/ListDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/ListDeadlineCommandSequenceDiagram.puml
  src/main/java/seedu/duke/Parser.java
Labels: type.Bug, priority.High, severity.Low

#189 Fix DG and UG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/darrenlsx.md
Labels: type.Bug, priority.Medium, severity.Medium

#190 Add messages for module adding and deleting modules
  src/main/java/seedu/duke/ModuleStorage.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/AddModuleCommand.java
  src/test/java/seedu/duke/UITest.java
Labels: type.Enhancement, severity.Low

#191 Updated Architecture Diagram
  docs/DeveloperGuide.md
  docs/diagrams/Architecture Diagram.png
  docs/diagrams/Architecture.png
  docs/diagrams/Architecture.puml
  docs/diagrams/Commands/ListPuCommandSequenceDiagram.puml
Labels: priority.High

#192 [Task] Update sd and user guide description
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Commands/ListCurrentCommandSequenceDiagram.png
  docs/diagrams/Commands/ListCurrentCommandSequenceDiagram.puml
  docs/diagrams/Commands/ListCurrentPuCommandSequenceDiagram.png
  docs/diagrams/Commands/ListCurrentPuCommandSequenceDiagram.puml
  docs/diagrams/Commands/ListPuCommandSequenceDiagram.png
  docs/diagrams/Commands/ListPuModulesCommandSequenceDiagram.png
  docs/diagrams/Commands/ListPuModulesCommandSequenceDiagram.puml
Labels: type.Task, priority.High, severity.Low

#194 Fix Search function bug and update DG and SD to reflect class changes
  docs/DeveloperGuide.md
  docs/diagrams/DukeHighLevel.png
  docs/diagrams/DukeHighLevel.puml
  docs/diagrams/DukeInitialisation.png
  docs/diagrams/DukeInitialisation.puml
  docs/diagrams/Storage/Storage.png
  docs/diagrams/Storage/Storage.puml
  docs/diagrams/Storage/StorageAddModule.png
  docs/diagrams/Storage/StorageAddModule.puml
  docs/diagrams/Storage/StorageClassDiagram.png
  docs/diagrams/Storage/StorageClassDiagram.puml
  docs/diagrams/Storage/readModData.png
  docs/diagrams/Storage/readModData.puml
  docs/diagrams/budget/EditAccommodationCommand.png
  docs/diagrams/budget/EditAccommodationCommand.puml
  docs/diagrams/budget/EditAirplaneTicketCommand.png
  docs/diagrams/budget/EditAirplaneTicketCommand.puml
  docs/diagrams/budget/EditBudgetCommand.png
  docs/diagrams/budget/EditBudgetCommand.puml
  docs/diagrams/budget/EditEntertainmentCommand.png
  docs/diagrams/budget/EditEntertainmentCommand.puml
  docs/diagrams/budget/EditFoodCommand.png
  docs/diagrams/budget/EditFoodCommand.puml
  docs/diagrams/budget/ViewBudgetCommand.png
  docs/diagrams/budget/ViewBudgetCommand.puml
  docs/diagrams/budget/budgetClassDiagram.png
  docs/diagrams/budget/budgetClassDiagram.puml
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/budget/Accommodation.java
  src/main/java/seedu/duke/budget/AirplaneTicket.java
  src/main/java/seedu/duke/budget/BudgetPlanner.java
  src/main/java/seedu/duke/budget/BudgetStorage.java
  src/main/java/seedu/duke/budget/Entertainment.java
  src/main/java/seedu/duke/budget/Food.java
  src/main/java/seedu/duke/budget/GoodsAndServices.java
  src/main/java/seedu/duke/command/AddModuleCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/EditAccommodationCommand.java
  src/main/java/seedu/duke/command/EditAirplaneTicketCommand.java
  src/main/java/seedu/duke/command/EditBudgetCommand.java
  src/main/java/seedu/duke/command/EditEntertainmentCommand.java
  src/main/java/seedu/duke/command/EditFoodCommand.java
  src/main/java/seedu/duke/command/ViewBudgetCommand.java
  src/test/java/seedu/duke/command/ListFoundNusModsCommandTest.java
Labels: type.Bug, priority.High

#195 Fix Listcurrentpu modules commad in parser
  src/main/java/seedu/duke/Parser.java
Labels: type.Bug, priority.High, severity.High

#196 Update Javadocs and UG
  docs/UserGuide.md
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.png
  docs/diagrams/Commands/DeleteModuleCommandSequenceDiagram.puml
  docs/diagrams/Commands/HelpCommandSequenceDiagram.png
  docs/diagrams/Commands/HelpCommandSequenceDiagram.puml
  docs/diagrams/Storage/Storage.png
  docs/diagrams/Storage/Storage.puml
  src/main/java/seedu/duke/DeadlineStorage.java
  src/main/java/seedu/duke/ModuleStorage.java
  src/main/java/seedu/duke/Parser.java
Labels: type.Enhancement, type.Bug, priority.Medium, severity.Medium

#197 Update DG deadline class diagram
  docs/diagrams/Deadline/DeadlineClassDiagram.png
  docs/diagrams/Deadline/DeadlineClassDiagram.puml
  src/main/java/seedu/duke/DeadlineStorage.java
Labels: type.Bug, priority.Medium, severity.Medium

#199 Update PPP
  docs/team/darrenlsx.md
Labels: type.Enhancement, priority.Low, severity.VeryLow

#203 Update darren's PPP and DG
  docs/DeveloperGuide.md
  docs/team/darrenlsx.md
Labels: type.Bug, priority.Low, severity.VeryLow

#204 Fix AboutUs Doc to show PPPs
  docs/AboutUs.md
Labels: priority.High

#205 Update /help command with "/search /mods" and filters
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement, priority.Medium

#206 Add NFR and Glossary, update PPP, AboutUs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/sszewen.md
Labels: type.Task, priority.High

#207 Branch update user guides
  docs/UserGuide.md
  src/main/java/seedu/duke/UI.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Task

#208 Change name from Duke to SEPHelper
  docs/diagrams/Deadline/AddDeadlineCommandSequenceDiagram.png
  docs/diagrams/Deadline/AddDeadlineCommandSequenceDiagram.puml
  docs/diagrams/DukeHighLevel.png
  docs/diagrams/DukeHighLevel.puml
  docs/diagrams/DukeInitialisation.png
  docs/diagrams/DukeInitialisation.puml
  docs/diagrams/Storage/Storage.png
  docs/diagrams/Storage/Storage.puml
Labels: type.Enhancement, priority.High

#210 [Task] Ug instructions for manual testing
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#213 Update User Guides & JavaDocs
  docs/UserGuide.md
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/ListFoundNusModsCommand.java
  src/main/java/seedu/duke/command/ListMappableNusModsCommand.java
Labels: type.Task, priority.Medium

#215 Fix bugs in DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium, severity.High

#217 Update parser sequence diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ParserSequenceDiagram.png
  docs/diagrams/ParserSequenceDiagram.puml
  docs/diagrams/remove/ExitCommand.png
  docs/diagrams/remove/ExitCommand.puml
  docs/diagrams/remove/prepareAddModuleCommand.png
  docs/diagrams/remove/prepareAddModuleCommand.puml
  docs/diagrams/remove/prepareListCommand.png
  docs/diagrams/remove/prepareListCommand.puml
  docs/diagrams/remove/prepareSearchByNusModCode.png
  docs/diagrams/remove/prepareSearchByNusModCode.puml
Labels: type.Task, priority.Medium

#219 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/remove/prepareSearchByNusModCode.png
  docs/diagrams/remove/prepareSearchByNusModCode.puml
  docs/team/johndoe.md
Labels: type.Task, priority.Medium

#220 Update AboutUs
  docs/DeveloperGuide.md
  docs/README.md
Labels: priority.High

#216 Update Developer Guide Budget Commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/remove/prepareListCommand.png
  docs/diagrams/remove/prepareListCommand.puml
Labels: type.Enhancement, priority.Medium

#221 Update PPP
  docs/team/briantjs00.md
Labels: type.Task

#222 Format budget DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High
